# Generated by Django 3.2.9 on 2023-11-26 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datapipeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
