# Generated by Django 3.2.9 on 2023-12-03 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datapipeline', '0003_remove_message_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomGPT',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('gpt_type', models.CharField(max_length=50)),
                ('instructions', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
