# Generated by Django 5.2.7 on 2025-10-21 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datapipeline', '0009_message_gpt_used_message_sent_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
